### ISSUE TITLE
Dinâmina de Lean Inception

### ISSUE THREAD

**Issue by icarooliv** [conosco/conosco-core#2]
T02 - Dinâmina de _Lean Inception_
---
### Descrição: 

Como não queremos desperdiçar tempo, dinheiro, nem esforço construindo um produto que não vai atender as expectativas de público, formato etc. Para isso, é preciso validar as hipóteses de negócio feitas na issue #1 e viabilizar possíveis passos de criação com o time todo. 

Da mesma forma, com um grupo de trabalho grande e muitas ideias surgindo, precisamos definir o escopo e colocar todo o time numa mesma visão e em um mesmo objetivo. Para que ao definirmos um MVP, consigamos evitar o caso de cada pessoa pensando algo diferente e assim implementarmos funcionalidades que fujam dos objetivos definidos. Visando, principalmente, a colaboração e valorizando a ideia de cada contribuidor. 

Dado o cenário, utilizaremos a metodologia _Lean Inception_, que vai ser mediada pela @AnaCarolcs.

### Tarefas

- [x] Escrever visão do produto colaborativamente
- [x] Esclarecer objetivo
- [x] É/Não é - Faz/Não faz
- [x] Mapa de Segmentação (definir o público alvo)
- [x] Personas
- [x] Quadrantes para identificar tipos de personas
- [x] Mapa de empatia

### Onde
FGA

### Quando
Quarta (20/03) ás 14h. Caso não tenhamos tempo, faremos às 14h no sábado (23/3).

**Comment by icarooliv** [comment]
A partir das dinâmicas de escrita de visão do produto e esclarecimento dos objetivos, além do que o nosso projeto faz ou não faz, foi possível extrair um Mapa de Segmentação ¹ para servir como base da nossa criação de Personas.

Partindo do princípio que possuímos contato com a comunidade de estudantes da FGA como insumo de pesquisas mercadológicas e até mesmo testes de usabilidade, escolhemos o público universitário como nosso alvo e a comunidade como nossa amostra para este. 

**Critério de Segmentação**

- Idade: 19-30 anos ¹
- Sexo: Todos
- Renda: >= 1,5 salários mínimos ³
- Ocupação: Estudantes universitários

**Geográfico**

- Pais: Brasil
- Região: Centro Oeste
- Estado: DF
- Município: Brasilia

**Comportamental** 

- Atitudes - Rotina movimentada, hiperatividade, falta de foco e disciplina.
- Comportamento de Compra - possui o habito de efetuar compras online, com cartão de crédito. Realizam assinaturas online. ⁴ 
- Utilização - utilizam primariamente serviços online. Disponibilizam muito tempo em dispositivos móveis com acesso a _internet_.

**Psicográfico**

- Valores - Possuem mais empatia, e atitudes colaborativas. ⁵
- Opiniões - Abertas a novas opiniões baseadas na experiência do próximo. 
- Crenças - Confiam menos em instituições tradicionais ⁶. 
- Grupos - São pessoas que não se limitam tanto a grupos, entretanto se aproximam de pessoas que possuem interesses em comum sem limitar suas relações.


Fontes:
¹ [Analise o mercado antes de tomar decisões](http://www.sebrae.com.br/sites/PortalSebrae/artigos/analise-o-mercado-antes-de-tomar-decisoes,500d7e0805b1a410VgnVCM1000003b74010aRCRD). SEBRAE. 2019.

² [Média de idade por área do conhecimento](http://g1.globo.com/sp/vale-do-paraiba-regiao/especial-publicitario/quero-bolsa/noticia/2017/02/quero-bolsa-faz-ranking-da-media-de-idade-dos-alunos-de-cada-curso.html). Globo. 2017. 

³ [Dois terços dos universitários das federais têm renda familiar de 1,5 salário mínimo](https://jornalggn.com.br/gestao/dois-tercos-dos-universitarios-das-federais-tem-renda-familiar-de-15-salario-minimo/
). Jornal GGN. 2018.

⁴ [Pesquisa revela o comportamento de consumo dos _millennials_](https://revistaglamour.globo.com/Lifestyle/Carreira-e-dinheiro/noticia/2017/11/pesquisa-revela-o-comportamento-de-consumo-dos-millennials.html_
). Revista Glamour. 2017.

⁵ [Dossiê BrandLab: The Millennial Divide](https://www.thinkwithgoogle.com/intl/pt-br/tendencias-de-consumo/dossie-brandlab-millennial-divide/). Google. 2017.

⁶ [The reason why millennials don't trust others](https://www.washingtonpost.com/news/monkey-cage/wp/2014/03/17/the-real-reason-why-millennials-dont-trust-others/?utm_term=.41e2437ea4ad). The Washington Post. 2014.

**Comment by AnaCarolcs** [comment]
_Lean Inception_ é o nome dado ao método colaborativo para alinhar um grupo de pessoas sobre o MVP (produto mínimo viável) que será desenvolvido. É uma sequência de atividades para alinhar e definir objetivos, estratégias e escopo do produto. 

O produto mínimo viável, em Inglês _Minimum Viable Product_ (MVP), é a versão mais simples de um produto que pode ser disponibilizada para o negócio. O MVP determina quais são as funcionalidades mais essenciais para que se tenha o mínimo de produto funcional que possa agregar valor para o negócio (produto mínimo) e que possa ser efetivamente utilizado e validado pelo usuário final (produto viável).

O nome _Inception_ vem do RUP (Rational Unified Process). _Inception_ é a primeira de quatro fases do RUP: _Inception, Elaboration, Construction e Transition_.  Na fase de _Inception_ era realizado a análise sobre os objetivos, a arquitetura e o planejamento do projeto. Isso acontecia via entrevistas com os _stakeholders_, convertidos em requisitos descritos no formato de casos de uso. 

Os casos de uso caíram em desuso e os métodos ágeis adotaram o formato de histórias do usuário, o que, como diz o próprio nome, é para os usuários. Atividades sobre os usuários e suas jornadas são feitas (influencia de design thinking e user-centric design); muitas histórias dos usuários são escritas, estimadas, arquitetadas e colocadas em um plano: o plano de release do produto.

No primeiro momentos, não focamos na criação de features e histórias de usuários. Foram feitas as dinâmicas de:

**Escrevendo a visão do procuto colaborativamente** 

**Esclarecendo o objetivo**

**O produto -É -Não é -Faz -Não faz**

**Quadrantes para identificar tipos de personas** 

**Mapa de empatia**

Segue o link da planilha com as respostas do time durante as dinâmicas:
(https://docs.google.com/spreadsheets/d/1_JSx749zhP-uB92-P7Z-27NneFoBGO80NMRsls7r1fk/edit?usp=sharing)

Fonte:
¹ [O que é o método Lean Inception](http://http://www.caroli.org/lean-inception/). Caroli. 2018.

**Comment by AnaCarolcs** [comment]
![photo4951755787009632317](https://user-images.githubusercontent.com/9967427/54891241-84fb6780-4e8b-11e9-83b6-ba0a5b1b89eb.jpg)
![photo4951847596230551596](https://user-images.githubusercontent.com/9967427/54891245-89c01b80-4e8b-11e9-8abf-15ecb6c5c6dc.jpg)
![photo4951847596230551597](https://user-images.githubusercontent.com/9967427/54891250-8f1d6600-4e8b-11e9-9be7-deb532533a23.jpg)
